@startuml
title Публикация карточек товаров на маркетплейсе

actor "Продавец" as Seller
participant "Система" as System

note over Seller, System
  <b>Цель:</b> Дать предпринимателю возможность публиковать карточки товаров 
  через личный кабинет для запуска продаж на маркетплейсе.

  <b>Предусловия:</b>
  - Пользователь авторизован
  - Подтверждён статус продавца (ИП\самозанятый\ООО)
end note

Seller -> System: Селлер открывает приложение или сайт.
System --> Seller: Система загружает и отображает главный экран.

Seller -> System: Продавец переходит в окно личного кабинета.
Seller -> System: Продавец нажимает на кнопку "Зарегистрировать новый товар".
System --> Seller: Система загружает и отображает форму регистрации нового товара.

Seller -> System: Продавец заполняет обязательные поля формы (название, цена, описание, изображение, категория, артикул, количество на складе).
Seller -> System: Продавец нажимает на кнопку "Опубликовать товар".

System --> Seller: Система перенаправляет продавца на экран с уведомлением о запущенной проверке данных о товаре.\nНа экране отображается статус проверки и внесенные в форму данные.\nПользователю снова доступна публикация нового товара.

alt Основной сценарий: проверка пройдена
    System --> Seller: После завершения проверки данных система обновляет статус на экране. Товар отображается как "опубликованный".
    System --> Seller: Система уведомляет продавца о завершении проверки уведомлением (push\email\sms).
    System --> Seller: На экране появляется ссылка для перехода к карточке товара. По ссылке отображается экран товара, предназначенный для покупателя.

else Альтернативный путь: данные не прошли проверку
    System --> Seller: Продавец получает уведомление с описанием причины.

else Альтернативный путь: отмена или изменения в процессе проверки
    Seller -> System: Продавец нажимает соответствующую кнопку в личном кабинете.
    System --> Seller: Завершение процесса проверки со статусом "отмена".
end

note over Seller, System
  <b>Постусловия:</b>
  Продавец опубликовал данные о своем товаре через личный кабинет, 
  товар доступен к покупке всем пользователям маркетплейса.
end note

@enduml